'use client';

import { LegalPageLayout } from '@/components/marketing/LegalPageLayout';

export default function PrivacyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="March 15, 2026">
      <p>
        At Aura.ai (&quot;Aura&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI-powered marketing platform, including our website, applications, and services (collectively, the &quot;Platform&quot;).
      </p>

      <h2>Information We Collect</h2>
      <h3>Information you provide</h3>
      <p>
        When you create an account, we collect your name, email address, organization name, and role. During onboarding, you may provide additional business information including your industry, target audience, brand voice preferences, and marketing goals.
      </p>
      <h3>Social media account data</h3>
      <p>
        When you connect social media accounts (LinkedIn, Twitter/X, Instagram, Facebook, TikTok, YouTube, Pinterest, or Google Business Profile), we receive OAuth tokens and profile information necessary to publish content and retrieve analytics on your behalf. We encrypt all OAuth tokens using AES-256-GCM before storing them.
      </p>
      <h3>Content and usage data</h3>
      <p>
        We collect content you create or generate using our AI tools, including drafts, published posts, email campaigns, images, and SEO analyses. We also collect usage data such as feature interactions, content performance metrics, and platform preferences.
      </p>
      <h3>Automatically collected information</h3>
      <p>
        We automatically collect device information, IP addresses, browser type, operating system, referral URLs, and interaction data through cookies and similar technologies.
      </p>

      <h2>How We Use Your Information</h2>
      <p>We use the information we collect to:</p>
      <ul>
        <li>Provide, maintain, and improve the Platform</li>
        <li>Generate AI-powered content recommendations and marketing suggestions</li>
        <li>Publish content to connected social media accounts on your behalf</li>
        <li>Compile analytics and performance reports across your connected channels</li>
        <li>Process subscription payments and manage billing</li>
        <li>Send transactional emails (account verification, approval notifications, billing receipts)</li>
        <li>Provide customer support and respond to inquiries</li>
        <li>Detect and prevent fraud, abuse, and security incidents</li>
        <li>Comply with legal obligations</li>
      </ul>

      <h2>Data Sharing</h2>
      <p>
        We do not sell your personal information. We share data only in the following circumstances:
      </p>
      <ul>
        <li><strong>Service providers:</strong> We use third-party services including Clerk (authentication), Firebase/Google Cloud Platform (hosting and storage), Stripe (payments), and AI model providers to operate the Platform.</li>
        <li><strong>Social media platforms:</strong> When you use our publishing features, content is transmitted to the social media platforms you have connected.</li>
        <li><strong>Agency-client relationships:</strong> If you are a client of an agency using Aura, your agency may access content and analytics within their workspace as configured by their account settings.</li>
        <li><strong>Legal requirements:</strong> We may disclose information to comply with applicable law, regulation, legal process, or enforceable governmental request.</li>
      </ul>

      <h2>Social Media Data</h2>
      <p>
        When you connect social media accounts to Aura, we access only the data necessary to provide our services. This includes profile information, post performance metrics, audience demographics, and publishing capabilities. We do not access private messages or personal social media content unrelated to your marketing activities.
      </p>
      <p>
        You can disconnect any social media account at any time from your workspace settings. Upon disconnection, we stop collecting new data from that platform. Previously collected analytics data is retained according to our data retention policy.
      </p>

      <h2>AI-Generated Content</h2>
      <p>
        Content generated by our AI features is created using your inputs (prompts, brand voice settings, and content preferences) combined with our AI models. We do not use your generated content to train AI models for other customers. Your content remains yours.
      </p>
      <p>
        AI-generated content may include text, images, email copy, and SEO recommendations. While we strive for high-quality output, you are responsible for reviewing and approving all AI-generated content before publication.
      </p>

      <h2>Cookies and Tracking</h2>
      <p>We use the following types of cookies:</p>
      <ul>
        <li><strong>Essential cookies:</strong> Required for authentication, security, and core Platform functionality.</li>
        <li><strong>Analytics cookies:</strong> Help us understand how users interact with the Platform to improve our services.</li>
        <li><strong>Preference cookies:</strong> Remember your settings and personalization choices.</li>
      </ul>
      <p>
        You can manage cookie preferences through your browser settings. Disabling essential cookies may prevent you from using certain Platform features.
      </p>

      <h2>Data Retention</h2>
      <p>
        We retain your account data for as long as your account is active. Content, analytics, and workspace data are retained for 24 months after account closure unless you request earlier deletion. Billing records are retained for 7 years as required by applicable tax and financial regulations.
      </p>
      <p>
        You can request data export or deletion at any time by contacting us at privacy@aura.ai or through your account settings.
      </p>

      <h2>Your Rights</h2>
      <p>Depending on your jurisdiction, you may have the right to:</p>
      <ul>
        <li>Access the personal information we hold about you</li>
        <li>Correct inaccurate or incomplete data</li>
        <li>Request deletion of your personal data</li>
        <li>Export your data in a portable format</li>
        <li>Restrict or object to certain data processing activities</li>
        <li>Withdraw consent where processing is based on consent</li>
        <li>Lodge a complaint with your local data protection authority</li>
      </ul>
      <p>
        To exercise any of these rights, contact us at <a href="mailto:privacy@aura.ai">privacy@aura.ai</a>. We will respond within 30 days.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        Aura is a business-to-business platform designed for professional use. We do not knowingly collect information from children under 16. If we learn that we have collected information from a child under 16, we will delete it promptly.
      </p>

      <h2>Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on our website and, where appropriate, by sending an email notification. Your continued use of the Platform after changes take effect constitutes your acceptance of the revised policy.
      </p>

      <h2>Contact</h2>
      <p>
        If you have questions about this Privacy Policy or our data practices, please contact us:
      </p>
      <ul>
        <li>Email: <a href="mailto:privacy@aura.ai">privacy@aura.ai</a></li>
        <li>Address: Aura Technologies Inc., 350 Fifth Avenue, Suite 4500, New York, NY 10118</li>
        <li>Data Protection Officer: <a href="mailto:dpo@aura.ai">dpo@aura.ai</a></li>
      </ul>
    </LegalPageLayout>
  );
}
