/**
 * F4: Calendar Service
 *
 * Manages calendar events — both auto-generated (from publish jobs,
 * approval deadlines, content due dates) and manually created.
 */

import { adminDb } from '@/lib/firebase/admin';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import type { CalendarEventType, CalendarEventStatus } from '@/types/features/content';

export async function createCalendarEvent(
  workspaceId: string,
  data: {
    title: string;
    description?: string;
    eventType: CalendarEventType;
    startAt: string;
    endAt?: string;
    timezone: string;
    allDay?: boolean;
    color?: string;
    linkedContentDraftId?: string;
    linkedPublishJobId?: string;
    linkedApprovalId?: string;
    linkedCampaignId?: string;
    linkedClientId?: string;
    notificationMinutesBefore?: number[];
    attendeeUserIds?: string[];
    isAutoGenerated?: boolean;
  },
  createdBy: string,
): Promise<string> {
  const eventRef = adminDb
    .collection('workspaces')
    .doc(workspaceId)
    .collection('calendar_events')
    .doc();

  await eventRef.set({
    id: eventRef.id,
    workspaceId,
    title: data.title,
    description: data.description ?? null,
    eventType: data.eventType,
    status: 'scheduled' as CalendarEventStatus,
    color: data.color ?? null,
    startAt: Timestamp.fromDate(new Date(data.startAt)),
    endAt: data.endAt ? Timestamp.fromDate(new Date(data.endAt)) : null,
    timezone: data.timezone,
    allDay: data.allDay ?? false,
    linkedContentDraftId: data.linkedContentDraftId ?? null,
    linkedPublishJobId: data.linkedPublishJobId ?? null,
    linkedApprovalId: data.linkedApprovalId ?? null,
    linkedCampaignId: data.linkedCampaignId ?? null,
    linkedClientId: data.linkedClientId ?? null,
    notificationMinutesBefore: data.notificationMinutesBefore ?? [],
    attendeeUserIds: data.attendeeUserIds ?? [],
    isAutoGenerated: data.isAutoGenerated ?? false,
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
    createdBy,
  });

  return eventRef.id;
}

/**
 * Auto-create a calendar event when a publish job is scheduled.
 */
export async function syncPublishJobToCalendar(
  workspaceId: string,
  publishJobId: string,
  contentTitle: string,
  scheduledAt: string,
  timezone: string,
  platforms: string[],
  createdBy: string,
): Promise<string> {
  return createCalendarEvent(
    workspaceId,
    {
      title: `Publish: ${contentTitle}`,
      description: `Scheduled to publish on ${platforms.join(', ')}`,
      eventType: 'publish',
      startAt: scheduledAt,
      timezone,
      color: '#FF4D00', // Brand orange for publish events
      linkedPublishJobId: publishJobId,
      isAutoGenerated: true,
    },
    createdBy,
  );
}

export async function listCalendarEvents(
  workspaceId: string,
  from: string,
  to: string,
  filters: {
    eventType?: string;
    linkedClientId?: string;
  } = {},
): Promise<Record<string, unknown>[]> {
  let query = adminDb
    .collection('workspaces')
    .doc(workspaceId)
    .collection('calendar_events')
    .where('startAt', '>=', Timestamp.fromDate(new Date(from)))
    .where('startAt', '<=', Timestamp.fromDate(new Date(to)))
    .orderBy('startAt', 'asc')
    .limit(200) as FirebaseFirestore.Query;

  if (filters.eventType) {
    query = query.where('eventType', '==', filters.eventType);
  }

  const snapshot = await query.get();
  return snapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      ...data,
      startAt: data.startAt?.toDate()?.toISOString() ?? null,
      endAt: data.endAt?.toDate()?.toISOString() ?? null,
    };
  });
}

export async function updateCalendarEvent(
  workspaceId: string,
  eventId: string,
  updates: Record<string, unknown>,
): Promise<void> {
  const eventRef = adminDb
    .collection('workspaces')
    .doc(workspaceId)
    .collection('calendar_events')
    .doc(eventId);

  // Convert date strings to Timestamps
  if (typeof updates.startAt === 'string') {
    updates.startAt = Timestamp.fromDate(new Date(updates.startAt as string));
  }
  if (typeof updates.endAt === 'string') {
    updates.endAt = Timestamp.fromDate(new Date(updates.endAt as string));
  }

  await eventRef.update({
    ...updates,
    updatedAt: FieldValue.serverTimestamp(),
  });
}

export async function deleteCalendarEvent(
  workspaceId: string,
  eventId: string,
): Promise<void> {
  await adminDb
    .collection('workspaces')
    .doc(workspaceId)
    .collection('calendar_events')
    .doc(eventId)
    .update({
      status: 'cancelled' as CalendarEventStatus,
      updatedAt: FieldValue.serverTimestamp(),
    });
}
