import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { FileText, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function PortalReportsPage() {
  // Mock reports — in production, fetch from clients/{clientId}/reports
  const reports = [
    { id: 'r1', title: 'Monthly Performance Report — March 2026', status: 'ready', generatedAt: '2026-03-31', format: 'pdf' },
    { id: 'r2', title: 'Monthly Performance Report — February 2026', status: 'ready', generatedAt: '2026-02-28', format: 'pdf' },
    { id: 'r3', title: 'Q4 2025 Quarterly Review', status: 'ready', generatedAt: '2025-12-31', format: 'pdf' },
  ];

  return (
    <div className="flex flex-col gap-6 p-6" data-testid="portal-reports">
      <h1 className="text-heading-xl font-display text-foreground">Reports</h1>
      <p className="text-body-sm text-muted-foreground">View and download reports generated by your agency.</p>

      <div className="space-y-3">
        {reports.map((report) => (
          <Card key={report.id}>
            <CardContent className="flex items-center justify-between py-4">
              <div className="flex items-center gap-3">
                <FileText className="size-5 text-brand-orange" />
                <div>
                  <p className="font-ui text-sm font-medium">{report.title}</p>
                  <p className="text-[11px] text-muted-foreground">Generated {report.generatedAt}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="text-[10px]">{report.format.toUpperCase()}</Badge>
                <Button variant="outline" size="sm"><Download className="size-3.5 mr-1" />Download</Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
